version: '3.8'

services:
  database:
    image: postgres:15-alpine
    container_name: kpd_database
    restart: always
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata

  backend:
    build: ./backend
    container_name: kpd_backend
    restart: always
    ports:
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      - database

  frontend:
    build: ./frontend
    container_name: kpd_frontend
    restart: always
    ports:
      - "8081:80"
    depends_on:
      - backend

volumes:
  pgdata: